spring:
  application:
    name: profile-service

server:
  port: 8081
  servlet:
    context-path: /profile

spring:
  neo4j:
    uri: bolt://localhost:7474
    authentication:
      username: neo4j
      password: 1234568
